### ISSUE TITLE
VS 2017 hangs with automatic installation on existing project

### ISSUE THREAD

**Issue by luedi** [andfomin/NgProjectTemplate#12]
While testing the template I created a new ASP.NET Core 2.0 project with the default Angular template. I tried to add your template to this project. This results in an endless loop inside Visual Studio. I tried to figure out the reason and found that my Node and Angular CLI installation was outdated (Node 6.10.x and Angular CLI 1.2.4). After upgrading to the latest version your template works.
I didn't find any prerequisites in the documentation. You should update it with the minimum Node and Angular CLI version needed.
Also, in my opinion, it makes no sense to apply your template on the default Angular template. I didn't test it, bur i can imagine that this has unwanted side effects.

Best Regards
Klaus

**Comment by Czaste** [comment]
I believe the intention of the template is to create a project that has a CLI client that is independent of the API server part of the application (as this is by design a limitation of CLI clients). As Andrey states in the instructions, you should apply his template to an existing .Net Core web application, but not to a .Net Core web app that has been created for Angular. 

These are really two completely different animals. I am working with him on port issues that may reflect what you are looking for as well. Take a look at the issues.

**Comment by andfomin** [comment]
If the template finds an `@angular/core` reference in package.json, it will disable the Automatic mode. The `ng new` command would report errors if it found a package.json file or a tsconfig.json file.
