### ISSUE TITLE
Proxy [Not Closed yet]

### ISSUE THREAD

**Issue by ranouf** [andfomin/NgProjectTemplate#14]
Hi,

Thanks for your template, really usefull!

I have a question for you, I would like to user a proxy like this:
https://vividcode.io/use-proxy-in-angular-cli/

But it seems doesnt work. 
I created the file proxy with
```
{
  "/api": {
    "target": "http://localhost:51799/", 
      "secure": false
  }
}
```

And I update packages.json with

`    "start": "ng serve",`
=> 
`    "start": "ng serve --proxy-config proxy.conf.json",`

How can I use a proxy with your template?

Thank you
Cedric

**Comment by ranouf** [comment]
In the command console, I have :
```
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 10% building modules 3/3 modules 0 activewebpack: wait until bundle finished: /
 28% building modules 157/184 modules 27 active ...s\modules\core.get-iterator-method.jswebpack: wait until bundle finished: /
Date: 2017-12-14T20:21:27.632Z
Hash: 6826ec2ad050d452570d
Time: 13081ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 50.2 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 562 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 34.3 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 8.45 MB [initial] [rendered]

webpack: Compiled successfully.
```

But if the  _--proxy-config proxy.conf.json_ was really included in the ng serve, it will suppose to show something like:
```
[HPM] Proxy created:
[HPM] Proxy rewrite rule created: "^/api" ~> ""
```

Just in case, following these intructions (https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/proxy.md), i updated my proxy.conf.json:
```
{
  "/api": {
    "target": "http://localhost:51799/",
    "secure": false,
    "changeOrigin": true,
    "pathRewrite": {
      "^/api": ""
    }
  }
}
```
It still continue to not work.

**Comment by ranouf** [comment]
I followed the instructions from the readme.md

> NG Development Server uses port 4200 by default. If that port is already in use, you may want to specify a different port. To do that, open the project's Properties page and select the Debug tab. Add an Environment Variable named ASPNETCORE_NgServeOptions and enter --port Number (for example --port 4201) as its Value. The Value stored in ASPNETCORE_NgServeOptions is passed to ng serve as is. You can use that setting to customize the NG Development Server. Find more about the options available in ng serve here.

So I added a new environment variable:
ASPNETCORE_NgServeOptions => --proxy-config proxy.conf.json

It still continue to not work.

**Comment by andfomin** [comment]
Hi Cedric,

I'm sorry for discovering the question late. 

Based on your doc quote, I assume you use the Project Template (as opposed to Item Template). First, you need to make your Angular CLI project work if you start it from a Command Prompt by typing `ng serve` manually, not from Visual Studio. After you have succeeded with the settings, assign the options to `ASPNETCORE_NgServeOptions`. By the way, the template does not use the `start` command in package.json. It calls `ng serve` directly and appends the value from `ASPNETCORE_NgServeOptions`

If you use Item Template, the first goal is the same. Make sure you can run `ng serve` manually as expected.

**Comment by ranouf** [comment]
Hi,

I prefer the solution where everything is manage by VS including the launch of the ng serve.  
But from I understand in your response, to use a proxy, there is no other option than using the Command Prompt. Am I right?

**Comment by andfomin** [comment]
The Project Template launches an `ng serve` process itself during project startup and redirects the browser to the lunched NG server. If the port is taken at this moment by another instance, for example started manually, the template will raise error. 

I advised you to start `ng serve` manually for test purposes, to make sure your setup can work at all. Because the template creates a pure Angular CLI app.

You mentioned "proxy" in your question. Proxy is used by the Item Template. That's a different case. In that case you could launch NG server manually, but you don't need to.

By default, the proxy will launch `ng serve` during the project startup from VS with the options string passed to it as a parameter in code. It will wait until the NG server is ready before starting proxying requests. The NG server will be shut down/restarted on project stop/restart.

But if the proxy finds out that the port is already taken, it will assume an NG server has been launched manually and will proxy to the running instance. This way you can save time when you restart your project frequently. The Hot Module Replacement feature still works in this case.
